home/urls.py
from django.urls import path
from .views import *


urlpatterns = [
     path( r'' , index, name='home' ),
 ]

vehicle/urls.py
from django.urls import path
from .views import *

urlpatterns = [
	path(r'', index, name='vehicle_index'),
	path(r'<str:vehicle_number>/view/', view, name='vehicle_view')
]

vehicle/models.py
from django.db import models
from drivers.models import Driver, Staff
from route.models import RouteInfo
from choices import vehicle_color, vehicle_type, vehicle_status


class VehicleInfo(models.Model):
	vehicle_number = models.CharField(max_length=50, verbose_name='Vehicle ID', unique=True, default="")
	color = models.CharField(max_length=20, choices=vehicle_color, verbose_name='Color')
	vehicle_type = models.CharField(max_length=20, choices=vehicle_type, default=0, verbose_name='Type')
	license_number = models.CharField(max_length=100, verbose_name='License No.')
	engine = models.CharField(max_length=100, blank=True, verbose_name='Engine')
	capacity = models.IntegerField(verbose_name='Capacity')
	status = models.CharField(max_length=20, choices=vehicle_status, default=0, verbose_name='Status')
	route = models.ForeignKey(RouteInfo, on_delete=models.CASCADE, verbose_name='Route')
	driver = models.OneToOneField(Driver, null=True, blank=True, on_delete=models.CASCADE, limit_choices_to={'is_free': True})
	staff = models.OneToOneField(Staff, null=True, blank = True, on_delete = models.CASCADE, limit_choices_to={'is_free': True})
	is_scheduled = models.BooleanField(default=False, verbose_name='Scheduled', blank=True)

	def __str__(self):
		return '{}'.format(self.vehicle_number)

vehicle/forms.py
from django import forms
from .models import VehicleInfo


class VehicleForm(forms.Form):
	vehicle = forms.ModelChoiceField(queryset = VehicleInfo.objects.all(), empty_label = 'All', required = False)

vehicle/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect

from transport_schedule.models import TransportSchedule
from .models import VehicleInfo


def index(request, **kwargs):
	vehicle = VehicleInfo.objects.all()
	return render(request, 'vehicle/index.html', {'vehicle': vehicle, 'title': 'Vehicle List' })


def view(request, vehicle_number, **kwargs):
	vehicle = VehicleInfo.objects.get(vehicle_number=vehicle_number, is_scheduled=True)
	schedule = TransportSchedule.objects.get(vehicle_route=vehicle_number)
	return render(request, 'vehicle/view.html', {
		'vehicle': vehicle,
		'title': vehicle.vehicle_number,
		'schedule': schedule,
	})

templates/vehicle/index.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}">{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
<div id="content-main">
<div class="module">
</div>
</div>
{% endblock %}
{% block sidebar %}
<div id="content-related">
    <table class="table-overview" style="width:960px; margin-left:60px">
            <caption><a href="{% url 'vehicle_index' %}" class="section">Vehicle List</a></caption>
           <tr style="text-align:center; color:purple">
               <td>Vehicle</td>
               <th style="text-align:center">Type</th>
               <th style="text-align:center">Capacity</th>
                <th style="text-align:center">Route</th>
                <th style="text-align:center">Driver</th>
               <th style="text-align:center">Driver Contact</th>
                <th style="text-align:center">Staff</th>
                <th style="text-align:center">Status</th>
           </tr>
              {% if vehicle %}
              {% for row in vehicle %}
              <tr style="text-align:center">
                  <td><a href="{% url 'vehicle_view' row.vehicle_number %}">{{ row.vehicle_number }}</a></td>
              <td>{{ row.get_vehicle_type_display }}</td>
              <td>{{ row.capacity }}</td>
              <td>{{ row.route.display_text }}</td>
              <td>{{ row.driver }}</td>
              <td>{{ row.driver.phone_number }}</td>
              <td>{{ row.staff }}</td>
              <td>{{ row.get_status_display }}</td>
              </tr>
              {% endfor %}
              {% else %}
                <tr>
                <th colspan="4" style="text-align:center"> <p>Sorry! &#x1F60C;</p> No Vehicle to view</th>
                </tr>
              {% endif %}
          </table>
</div>

{% endblock %}