home/urls.py
from django.urls import path
from .views import *


urlpatterns = [
     path( r'' , index, name='home' ),
 ]

ticketing/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path(r'<str:ticket_number>/print/', SaleInvoice.as_view(), name='sale_invoice'),
    path(r'add/', add, name='ticket_add'),
    path(r'', index, name='ticket_index'),
    path(r'api/ticket_data/', ticket_sale_data, name='ticket_sale_data'),
    path(r'payment/', ticket_payment, name='ticket_payment'),
]

ticketing/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Q

from choices import ticket_types, ticket_status, payment_types
from vehicle.models import VehicleInfo


def vehicles():
    vehicle_info = VehicleInfo.objects.filter(Q(is_scheduled=True) & Q(status__in=[0, 2]))
    return {'pk__in': vehicle_info}


class TicketSale(models.Model):
    ticket_type = models.CharField(max_length=200, choices=ticket_types, verbose_name='Type', default=ticket_types[0][0])
    vehicle_id = models.ForeignKey(VehicleInfo, on_delete=models.CASCADE, limit_choices_to=vehicles, null=True, blank=True)
    issued_for = models.CharField(max_length=200)
    status = models.CharField(max_length=200, choices=ticket_status, verbose_name='Status', default=ticket_status[0][0])
    applied_date = models.DateField(auto_now_add=False)
    expiry_date = models.DateField(blank=True, null=True)
    issued_by = models.CharField(blank=True, null=True, default='', max_length=200)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Total')
    paid_amount = models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Paid Amount', blank=True, null=True, default=0)
    payment_type = models.CharField(max_length=200, choices=payment_types)
    payment_date = models.DateField(blank=True, null=True, verbose_name='Payment Date')
    ticket_number = models.CharField(max_length=300, verbose_name='Ticket No.')
    voucher_number = models.CharField(max_length=300)
    braintree_id = models.CharField(max_length=150, blank=True)

    class Meta:
        db_table = 'sale_invoice'

    @property
    def due(self):
        return self.total_amount - self.paid_amount

    @property
    def unit_price(self):
        return TicketInfo.objects.get(ticket_type=self.ticket_type).unit_price

    @property
    def discount(self):
        unit_price = self.unit_price
        actual_amount = int(self.ticket_type)*unit_price
        discount_amount = actual_amount-self.total_amount
        if discount_amount > 0:
            return discount_amount
        return None


class TicketInfo(models.Model):
    ticket_type = models.CharField(max_length=200, choices=ticket_types, verbose_name='Type',
                                   default=ticket_types[0][0])
    unit_price = models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Unit Price')
    created_by = models.CharField(max_length=200)
    created_date = models.DateField(auto_now_add=True)
    updated_by = models.CharField(max_length=200)
    updated_date = models.DateField(auto_now=True)

    class Meta:
        db_table = 'ticket_info'


class TicketDiscount(models.Model):
    discount = models.IntegerField(default=0, blank=True)
    discount_purpose = models.TextField(max_length=500, verbose_name='Purpose', blank=True)
    start_date = models.DateField()
    end_date = models.DateField()
    # status = models.CharField(max_length=200, choices=discount_status, default=discount_status[0][0])

    class Meta:
        db_table = 'discounts'

ticketing/forms.py
from django import forms
from .models import TicketSale


class TicketForm(forms.ModelForm):
    class Meta:
        model = TicketSale
        fields = ['vehicle_id', 'ticket_type', 'payment_type']

ticketing/views.py
import datetime

import braintree
from django.db.models import Count
from django.contrib import messages
from django.http import JsonResponse
from UTMS.settings import client
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import View
from django.shortcuts import render, redirect, get_object_or_404
from django.core import serializers
from render import Render
from .forms import TicketForm
from .models import TicketSale, TicketInfo


class SaleInvoice(View):

    def get(self, request, ticket_number):
        tickets = TicketSale.objects.get(ticket_number = ticket_number)
        prev = tickets.ticket_number[2:]
        # import pdb; pdb.set_trace()
        tickets.invoice = 'PI-'+prev
        params = {
            'university': client,
            'tickets': tickets,
            'request': request
        }
        return Render.render('pdf/sale_invoice.html', params)


def add(request, **kwargs):
    # import pdb; pdb.set_trace()
    if request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            ticket_type = request.POST['ticket_type']
            payment_type = request.POST['payment_type']
            unit_price = TicketInfo.objects.get(ticket_type=ticket_type).unit_price
            tick_num = TicketSale.objects.last()
            if tick_num:
                ticket_number = 'T-'+str(int(tick_num.ticket_number[2:])+1)
            else:
                ticket_number = 'T-101'
            # if discount != 0:
            #     total = float(unit_price)*int(ticket_type) - ((float(unit_price)*int(ticket_type))*(discount/100))
            # else:
            #     total = float(unit_price)*int(ticket_type)
            query = TicketSale.objects.create(
                ticket_type=ticket_type,
                payment_type=payment_type,
                issued_for=request.user.username,
                applied_date=datetime.datetime.now(),
                # expiry_date=expiry_date,
                issued_by='',
                total_amount=float(unit_price)*int(ticket_type),
                ticket_number=ticket_number,
                voucher_number=''
            )
            request.session['ticket_number'] = ticket_number
            query.save()
        # import pdb;
        # pdb.set_trace()
        if request.POST.get('submit', False):
            messages.success(request, 'Thank you for using UTMS. You will be notified your status soon!')
            return redirect('ticket_index')
        elif request.POST.get('checkout', False):
            return redirect('ticket_payment')
        else:
            form = TicketForm
            messages.success(request, 'Thank you for using UTMS. You will be notified your status soon!')
            return render(request, 'ticketing/add.html', {'form': form, 'title': 'Buy Ticket'})
    form = TicketForm()
    return render(request, 'ticketing/add.html', {'form': form, 'title': 'Buy Ticket'})


def index(request, **kwargs):
    tickets = TicketSale.objects.filter(issued_for=request.user.username)
    return render(request, 'ticketing/index.html', {'tickets': tickets})


def ticket_sale_data(request, **kwargs):
    from_date = (datetime.datetime.now() - datetime.timedelta(days=6)).date()
    to_date = datetime.datetime.today()
    data = TicketSale.objects.filter(applied_date__range=(from_date, to_date)).values('applied_date').annotate(
        tickets=Count('id')
    )
    return JsonResponse(list(data), safe=False)


def ticket_payment(request):
    ticket_number = request.session.get('ticket_number')
    ticket = get_object_or_404(TicketSale, ticket_number=ticket_number)
    if request.method == 'POST':
        # retrieve nonce
        nonce = request.POST.get('payment_method_nonce', None)
        # create and submit transaction
        result = braintree.Transaction.sale({
            'amount': '{:.2f}'.format(ticket.total_amount),
            'payment_method_nonce': nonce,
            'options': {
                'submit_for_settlement': True
            }
        })
        if result.is_success:
            # store the unique transaction id
            ticket.paid_amount=ticket.total_amount
            ticket.braintree_id = result.transaction.id
            ticket.save()
            messages.success(request, 'Thank you for using UTMS. Your payment is done successfully!')
            return redirect('ticket_index')
        else:
            ticket.delete()
            del request.session['ticket_number']
            request.session.modified = True
            form = TicketForm
            messages.success(request, 'Your Payment is not successful please try again')
            return render(request, 'ticketing/add.html', {'form': form, 'title': 'Buy Ticket'})
    else:
    # generate token
        client_token = braintree.ClientToken.generate()
        return render(request,
                      'ticketing/payment.html',
                      {'order': ticket,
                       'client_token': client_token})

templates/ticketing/add.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}">{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
<div id="content-main">
    <form method="post" class="post-form">{% csrf_token %}
        <div align="center">
            <table class="table-overview">
                <caption><a href="{% url 'ticket_index' %}" class="section">Your Tickets</a></caption>
            {{form.as_table}}
                </table>
        </div>

        <br>
        <div align="center" id="submit_line">
            <input type="submit" name="submit" class="btn btn-high btn-success" style="width:127px" value="Submit">
            <input type="submit" name="another" class="btn btn-high btn-success" style="width:157px" value="Submit and Add Another">
        </div>
    </form>
        </div>
<script type="text/javascript" src="../../static/js/payment.js"></script>
<script type="text/javascript">
ticket_payment();
</script>
{% endblock %}

{% block sidebar %}
<div id="content-related">
</div>

{% endblock %}

templates/ticketing/index.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}">{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
<div id="content-main">
    <table class="table-overview" style="width:960px; margin-left: 60px;">
            <caption><a href="{% url 'ticket_index' %}" class="section">Your Tickets</a></caption>
           <tr style="color:purple; text-align: center">
               <td >Ticket Number</td>
               <td>Ticket Type</td>
               <td>Status</td>
               <td>Expiry Date</td>
               <td>Unit Price</td>
               <td>Total</td>
               <td>Discount</td>
               <td>Due</td>
           </tr>
              {% if tickets %}
              {% for row in tickets %}
                {% if row.due <= 15 %}
              <tr style="text-align: center">
              <td>{{ row.ticket_number }}</td>
              <td>{{ row.get_ticket_type_display }}</td>
              <td>{{ row.get_status_display }}</td>
              <td>{{ row.expiry_date }}</td>
              <td>{{ row.unit_price }}</td>
              <td>{{ row.total_amount }}</td>
              <td>{{ row.discount }}</td>
              <td>{{ row.due }}</td>
              </tr>
        {% endif %}
              {% endfor %}
              {% else %}
                <tr>
                <th colspan="6" style="text-align:center">
                    <p>Sorry! &#x1F60C;</p>
                    You didn't buy any ticket yet
                </th>
                </tr>
              {% endif %}
          </table>
    <a type="submit" href="{% url 'ticket_add' %}" class="btn btn-high btn-success" style="width:127px; margin-left: 60px;" >Add</a>
        </div>
{% endblock %}

{% block sidebar %}
<div id="content-related">
</div>
{% endblock %}

templates/ticketing/payment.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}">{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
<h1>Pay by credit card</h1>
<form action="." id="payment" method="post">
<label for="card-number">Card Number</label>
<input id="card-number" class="field">
<label for="cvv">CVV</label>
<input id="cvv" class="field">
<label for="expiration-date">Expiration Date</label>
<input id="expiration-date" class="field">
<input type="hidden" id="nonce" name="payment_method_nonce" value="">
{% csrf_token %}
<input type="submit" value="Pay">
</form>
<!-- Load the required client component. -->
<script src="https://js.braintreegateway.com/web/3.29.0/js/client.min.js">
</script>
<!-- Load Hosted Fields component. -->
<script src="https://js.braintreegateway.com/web/3.29.0/js/hostedfields.
min.js"></script>
<script type="text/javascript" src="../../static/js/payment.js"></script>
<script>
    paymentProcess();
</script>
{% endblock %}

{% block sidebar %}
<div id="content-related">
</div>
{% endblock %}