complaint/urls.py
from django.urls import path
from .views import *

urlpatterns = [
	path(r'', index, name='complaint_index'),
	path(r'add/', add, name='complaint_add'),
	path(r'<int:complaint_id>/edit/', edit, name='complaint_edit'),
]

home/urls.py
from django.urls import path
from .views import *


urlpatterns = [
     path( r'' , index, name='home' ),
 ]

complaint/models.py
import datetime

from django.core.exceptions import ValidationError
from django.db import models
from choices import complaint_type, complaint_status, complaint_feedback
from vehicle.models import VehicleInfo


def no_future(value):
    today = datetime.datetime.today().date()
    if value > today:
        raise ValidationError('You can not provide future date!')


class Complaint(models.Model):
    complaint_type = models.CharField(max_length=100, choices=complaint_type, verbose_name='Type', default=complaint_type[0][0])
    incident_date = models.DateField(help_text="Enter the date of incident", blank=True, verbose_name='Incident Date', validators=[no_future])
    complaint_date = models.DateField(verbose_name='Complaint Date', auto_now_add=True)
    complaint_by = models.CharField(max_length=200, blank = False)
    accepted_by = models.CharField(max_length=100, verbose_name='Accepted By', default='None')
    updated_by = models.DateField(auto_now=True)
    status = models.CharField(max_length=200, choices=complaint_status, default=complaint_status[0][0])
    bus_number = models.ForeignKey(VehicleInfo, on_delete=models.CASCADE, default='', blank=True, null=True, verbose_name='Vehicle')
    description = models.TextField(max_length=500, blank=True)
    feedback = models.CharField(max_length=200, choices=complaint_feedback, blank=True, null=True, default='')

    def __str__(self):
        return "{}".format(self.complaint_type)

    class Meta:
        ordering = ['complaint_type', 'complaint_date']
        permissions = [('can_change_status', 'Can Update Status')]

complaint/forms.py
from django import forms
from .models import Complaint


class ComplaintForm(forms.ModelForm):
	class Meta:
		model = Complaint
		exclude = ['complaint_by', 'accepted_by', 'status']
		widgets = {
			'incident_date': forms.DateInput(attrs={'type': 'date'})
		}


class ComplaintFeedbackForm(forms.ModelForm):
	class Meta:
		model = Complaint
		fields = ['feedback', 'description']

complaint/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .forms import ComplaintForm, ComplaintFeedbackForm
from django.contrib import messages
from .models import Complaint


def index(request):
	complaint = Complaint.objects.filter(complaint_by=request.user)
	return render(request, 'complaint/index.html', {'complaint': complaint, 'title': 'Complaint List'})


def add(request, **kwargs):
	if request.method == 'POST':
		form = ComplaintForm(request.POST)
		if form.is_valid():
			complaint_type = request.POST['complaint_type']
			incident_date = request.POST['incident_date']
			vehicle_no = request.POST['bus_number']
			description = request.POST['description']
			complaint_by = str(request.user)
			accepted_by = ''
			query = Complaint.objects.create(
				complaint_type=complaint_type,
				incident_date=incident_date,
				bus_number_id=vehicle_no,
				description=description,
				complaint_by=complaint_by,
				accepted_by=accepted_by
			)
			query.save()
		if request.POST.get('submit', False):
			return redirect('complaint_index')
		else:
			form = ComplaintForm
			messages.error(request, 'Your complaint can not be filed. Check error please.')
			return render(request, 'complaint/add.html', {'form': form, 'title': 'Complaint Add'})
	form = ComplaintForm
	return render(request, 'complaint/add.html', {'form': form, 'title': 'Complaint Add'})


def edit(request, complaint_id, **kwargs):
	complaint = get_object_or_404(Complaint, pk=complaint_id)
	if request.method == 'POST':
		form = ComplaintFeedbackForm(request.POST, instance=complaint)
		if form.is_valid():
			complaint = form.save()
			messages.success(request, "Your Feedback Updated Successfully. Thank you!")
			return redirect('home')
	else:
		form = ComplaintFeedbackForm(instance=complaint)
	# import pdb; pdb.set_trace()
	return render(request, 'complaint/complaint_edit.html', {'form': form })

templates/complaint/add.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}">{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
<div id="content-main">
    <form method="post" class="post-form">{% csrf_token %}
        <div align="center">
            <table class="table-overview">
                <caption><a href="{% url 'complaint_index' %}" class="section">Complaint Box</a></caption>
            {{form.as_table}}
                </table>
        </div>

        <br>
        <div align="center">
            <input type="submit" name="submit" class="btn btn-high btn-success" style="width:127px" value="Submit">
            <input type="submit" name="another" class="btn btn-high btn-success" style="width:157px" value="Submit and Add Another">
        </div>
    </form>
        </div>

{% endblock %}

{% block sidebar %}
<div id="content-related">
</div>
{% endblock %}

templates/complaint/complaint_edit.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}">{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
<div id="content-main">
    <form method="post" class="post-form">{% csrf_token %}
        <div align="center">
            <table class="table-overview">
                <caption><a href="{% url 'complaint_index' %}" class="section">Update Feedback</a></caption>
            {{form.as_table}}
                </table>
        </div>

        <br>
        <div>
            <input type="submit" name="submit" class="btn btn-high btn-success" style="width:127px" value="Update">
        </div>
    </form>
        </div>
{% endblock %}

{% block sidebar %}
<div id="content-related">
</div>
{% endblock %}

templates/complaint/index.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}">{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
<div id="content-main">
    <span>
						{% if messages %}
							<ul class="messages">
								{% for msg in messages %}
								<li>
									<div class="alert alert-{{msg.level_tag}}" role="alert">
									{{msg.message}}
									</div>
								</li>
								{% endfor %}
							</ul>
							{% endif %}
					</span>
    <table class="table-overview">
            <caption><a href="{% url 'complaint_index' %}" class="section">Complaint Box</a></caption>
           <tr style="color:purple">
               <td >Vehicle Number</td>
               <td>Complaint Type</td>
               <td>Incident Date</td>
               <td>Complaint Date</td>
               <td>Accepted By</td>
               <td>Status</td>
               <td>Action</td>
           </tr>
              {% if complaint %}
              {% for row in complaint %}
              <tr>
              <td>{{ row.bus_number }}</td>
              <td>{{ row.get_complaint_type_display }}</td>
              <td>{{ row.incident_date }}</td>
              <td>{{ row.complaint_date }}</td>
              <td>{{ row.accepted_by }}</td>
              <td>{{ row.get_status_display }}</td>
              <td><a href="{% url 'complaint_edit' row.id %}" ><i class="fa fa-edit" style="color: #6610f2"></i></a></td>
              </tr>
              {% endfor %}
              {% else %}
                <tr>
                <th colspan="6" style="text-align:center">
                    <p>Sorry! &#x1F60C;</p>
                    You didn't file any complaint yet
                </th>
                </tr>
              {% endif %}
          </table>
    <a type="submit" href="{% url 'complaint_add' %}" class="btn btn-high btn-success" style="width:127px" >Add</a>
        </div>
{% endblock %}

{% block sidebar %}
<div id="content-related">
</div>
{% endblock %}